apiVersion: v2
name: xfsc-postgresql-openbao
description: Bitnami PostgreSQL with OpenBao credential provisioning and ESO
type: application
version: 0.1.0
appVersion: "17"

dependencies:
  - name: postgresql
    version: "18.7.3"
    repository: "https://charts.bitnami.com/bitnami"
