global:
  security:
    allowInsecureImages: true

openbaoInit:
  enabled: true
  image:
    repository: node-654e3bca7fbeeed18f81d7c7.de-west-1.xaas.plus.cloud/dev-ops/secret-init-container
    tag: "latest"
    pullPolicy: Always
  serviceAccountName: infrastructure-resource-provisioner
  address: http://openbao.security.svc.cluster.local:8200
  authPath: kubernetes
  role: xfsc-infrastructure-resource-provisioner
  kv:
    mount: infrastructure
    path: ""
  values:
    postgres-password: '$RANDOM_64'
  transit:
    enabled: false
    engines: []

externalSecret:
  enabled: true
  apiVersion: external-secrets.io/v1
  refreshInterval: 15m
  store:
    name: openbao
    kind: SecretStore
  target:
    name: postgresql-root-auth
    creationPolicy: Owner
    deletionPolicy: Retain

resourceProvider:
  enabled: true
  name: ""
  scope: Cluster
  description: PostgreSQL connection provided by this Helm release.
  allow:
    namespaces: []
  sslMode: disable

postgresql:
  image:
    registry: docker.io
    repository: bitnami/postgresql
    tag: latest
  architecture: standalone
  auth:
    enablePostgresUser: true
    existingSecret: postgresql-root-auth
    secretKeys:
      adminPasswordKey: postgres-password
  primary:
    persistence:
      enabled: true
      size: 8Gi
