{{- if .Values.externalSecret.enabled }}
apiVersion: {{ .Values.externalSecret.apiVersion }}
kind: ExternalSecret
metadata:
  name: {{ .Values.tsig.existingSecret }}
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.openbao.secretStore.name }}
    kind: SecretStore
  target:
    name: {{ .Values.tsig.existingSecret }}
    creationPolicy: {{ .Values.externalSecret.target.creationPolicy }}
    deletionPolicy: {{ .Values.externalSecret.target.deletionPolicy }}
  data:
    - secretKey: {{ .Values.tsig.key }}
      remoteRef:
        key: {{ .Values.openbaoInit.secretPath | quote }}
        property: {{ .Values.tsig.key }}
{{- end }}