issuance-service:
  image:
    pullPolicy: Always
    tag: 1.5.7

  ingress:
   enabled: false

  podAnnotations: 
    inject.xfsc.io/enabled: "true"

  config:
    logLevel: info
    servingPort: 8080
