keycloak:
  auth:
    existingSecret: keycloak-init-secrets
    passwordSecretKey: "password"
    annotations: {}
  extraVolumes:
    - name: xfsc-themes
      emptyDir: { }
  extraVolumeMounts:
    - mountPath: /opt/bitnami/keycloak/themes
      name: xfsc-themes
      subPath: themes
  replicaCount: 1
  extraEnvVars:
    - name: KC_HOSTNAME_URL
      value: https://auth-cloud-wallet.DOMAIN
    - name: KC_HOSTNAME_ADMIN_URL
      value: https://auth-cloud-wallet.DOMAIN
  containerPorts:
    http: 8080
    https: 8443
    infinispan: 7800
  tls:
    enabled: true
    usePem: true
    existingSecret: xfsc-wildcard
  ingress:
    enabled: true
    ingressClassName: nginx
    pathType: ImplementationSpecific
    apiVersion: ""
    hostname: auth-cloud-wallet.DOMAIN
    path: "{{ .Values.httpRelativePath }}"
    servicePort: http
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
      nginx.ingress.kubernetes.io/configuration-snippet: |
        proxy_set_header X-Forwarded-For $host;       
        proxy_set_header X-Forwarded-Proto $scheme;       
        proxy_set_header Upgrade $http_upgrade;       
        proxy_set_header Connection 'upgrade';       
        proxy_set_header Host $host;
      nginx.ingress.kubernetes.io/proxy-buffer-size: 256k
      nginx.ingress.kubernetes.io/proxy-buffers-number: '4'
      cert-manager.io/cluster-issuer: letsencrypt-prod
    labels: { }
    tls: false
    selfSigned: false
    extraHosts: [ ]
    extraPaths: [ ]
    extraTls:
      - hosts:
          - auth-cloud-wallet.DOMAIN
        secretName: xfsc-wildcard
    secrets: [ ]
    extraRules: [ ]
  postgresql:
    enabled: true
    auth:
      username: xc_keycloak
      database: xfsc_keycloak
      existingSecret: keycloak-init-secrets
    architecture: standalone
