credential-offering-bootstrap:
  enabled: true

  image:
    repository: node-654e3bca7fbeeed18f81d7c7.ps-xaas.io/ocm-wstack
    name: credential-offering-bootstrap
    tag: "dev"

  nats:
    url: nats://nats.infrastructure.svc.cluster.local:4222
    issuanceSubject: issuer.dummycontentsigner.request

  resourceClaim:
    enabled: false
    provider: nats

  httpRoute:
    enabled: false