apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.issuer.name }}
spec:
  acme:
    email: {{ .Values.acme.email | quote }}
    server: {{ .Values.acme.server | quote }}

    privateKeySecretRef:
      name: {{ printf "%s-account-key" .Values.issuer.name }}

    solvers:
      - selector:
          dnsZones:
            - {{ .Values.rfc2136.zone | quote }}
        dns01:
          rfc2136:
            nameserver: {{ .Values.rfc2136.nameserver | quote }}
            tsigKeyName: {{ .Values.rfc2136.tsig.keyName | quote }}
            tsigAlgorithm: {{ .Values.rfc2136.tsig.algorithm | quote }}
            tsigSecretSecretRef:
              name: {{ .Values.rfc2136.secret.name }}
              key: tsig-secret