apiVersion: v1
appVersion: v1.0.0
description: Crypto Service Helm Chart
name: cryptoservice
version: 1.0.1
dependencies:
  - name: signer
    version: 2.0.0
    repository: oci://node-654e3bca7fbeeed18f81d7c7.ps-xaas.io/tsa