kubernetes-operator:
  image:
    tag: 2.4.0
  serviceAccount:
    create: false
    name: "openbao-provisioner"
  openbao:
   address: http://openbao.security.svc.cluster.local:8200
   role: openbao-provisioner