vault:
  global:
    enabled: true
  server:
    enabled: true
    # Setzen des Dev-Mode-Parameters
    dev: 
      enabled: true

      devRootToken: "test"

    # Setzen des Dev-Token (optional)
    # beachte: Das Dev-Token wird normalerweise vom Vault bei Dev-Start generiert
    # daher ist es nicht notwendig, dies hier anzugeben
    devRootToken: "test"

    # Weitere Optionen
    ha:
      enabled: false  # Setze auf true, wenn du High Availability benötigst
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
    config:
      backend:
        file:
          path: /vault/data
      listener:
        tcp:
          address: "0.0.0.0:8200"
          tls_disable: true  # TLS aktivieren, wenn notwendig