apiVersion: v2
name: dummycontentsigner
description: dummycontentsigner deployment
type: application
version: 1.0.13
appVersion: "1.0.0"
dependencies:
  - name: dummycontentsigner
    version: 2.3.3-oidvci10.helm
    repository: oci://node-654e3bca7fbeeed18f81d7c7.ps-xaas.io/ocm-wstack
