dummycontentsigner:
  image:
    tag: 0.0.0-dev2
    pullPolicy: Always

  podAnnotations: 
    inject.xfsc.io/enabled: "true"

  config:
    nats:
      url: nats://nats.NAMESPACE.svc.cluster.local:4222
      queuegroup: dummysigner
      requestTimeOut: 10s
