apiVersion: v2
name: xfsc-cloudnative-pg-operator
description: XFSC wrapper chart for the CloudNativePG operator
type: application
version: 0.1.0
appVersion: "1.27.0"

dependencies:
  - name: cloudnative-pg
    version: "0.29.0"
    repository: "https://cloudnative-pg.github.io/charts"
