provider: rfc2136

external-dns:
  provider: rfc2136

  policy: sync
  registry: txt
  txtOwnerId: xfsc

  sources:
    - gateway-httproute
    - gateway
    - service

  domainFilters:
    - example.com

  serviceMonitor:
    enabled: true

  extraArgs:
    - --rfc2136-host=bind9.infrastructure.svc.cluster.local
    - --rfc2136-port=53
    - --rfc2136-zone=example.com
    - --rfc2136-tsig-secret-alg=hmac-sha256
    - --rfc2136-tsig-secret-name=externaldns.
    - --rfc2136-tsig-axfr

  env:
    - name: EXTERNAL_DNS_RFC2136_TSIG_SECRET
      valueFrom:
        secretKeyRef:
          name: dns-tsig
          key: tsig-secret
