external-dns:
  sources:
    - gateway-httproute
  logLevel: debug
  policy: sync

  registry: txt
  enableGatewayListenerSets: true
  txtOwnerId: xfsc

  extraArgs:
    - --txt-prefix=reg-%{record_type}.
    - --managed-record-types=A
    - --exclude-record-types=AAAA

  domainFilters: []