pre-authorization-bridge:
  image: 
    pullPolicy: Always
    tag: "2.5.4-oidvci10"
  ingress:
   enabled: false

  podAnnotations: 
    inject.xfsc.io/enabled: "true"
  redis:
    provider: redis
  config:
    logLevel: debug
    servingPort: 8080
    oAuth:
      signerTopic: sign
    wellKnown:
      grant_types_supported:
        - urn:ietf:params:oauth:grant-type:pre-authorized_code
