pre-authorization-bridge:
  image: 
    pullPolicy: Always
    tag: "main"
  ingress:
   enabled: false

  config:
    logLevel: debug
    servingPort: 8080
    oAuth:
      signerTopic: sign
    wellKnown:
      grant_types_supported:
        - urn:ietf:params:oauth:grant-type:pre-authorized_code
