apiVersion: xfsc.dev/v1alpha1
kind: ResourceProvision
metadata:
  name: did-resolver
spec:
  type: service
  outputs:
    env:
     DID_RESOLVER: {{ printf "http://%s.%s.svc.cluster.local" (include "universal-resolver.serviceName" .) .Release.Namespace | quote }}