apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cass.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
data:
  configure.sh: |
    #!/usr/bin/env bash
    set -Eeuo pipefail
    cp -a /etc/cassandra/. /work/
    sed -ri 's|^cluster_name:.*|cluster_name: "'"${CASSANDRA_CLUSTER_NAME}"'"|' /work/cassandra.yaml
    sed -ri 's|^num_tokens:.*|num_tokens: '"${CASSANDRA_NUM_TOKENS}"'|' /work/cassandra.yaml
    sed -ri 's|^listen_address:.*|listen_address: '"${POD_IP}"'|' /work/cassandra.yaml
    sed -ri 's|^rpc_address:.*|rpc_address: 0.0.0.0|' /work/cassandra.yaml
    sed -ri 's|^broadcast_rpc_address:.*|broadcast_rpc_address: '"${POD_IP}"'|' /work/cassandra.yaml
    sed -ri 's|^endpoint_snitch:.*|endpoint_snitch: GossipingPropertyFileSnitch|' /work/cassandra.yaml
    sed -ri 's|^authenticator:.*|authenticator: PasswordAuthenticator|' /work/cassandra.yaml
    sed -ri 's|^authorizer:.*|authorizer: CassandraAuthorizer|' /work/cassandra.yaml
    sed -ri 's|^role_manager:.*|role_manager: CassandraRoleManager|' /work/cassandra.yaml
    cat > /work/cassandra-rackdc.properties <<PROPS
    dc=${CASSANDRA_DC}
    rack=${CASSANDRA_RACK}
    prefer_local=true
    PROPS
    mkdir -p /work/cassandra-env.sh.d
    cat > /work/cassandra-env.sh.d/xfsc.sh <<ENV
    MAX_HEAP_SIZE="${MAX_HEAP_SIZE}"
    HEAP_NEWSIZE="${HEAP_NEWSIZE}"
    ENV
