openbaoInit:
  enabled: true
  image:
    repository: node-654e3bca7fbeeed18f81d7c7.de-west-1.xaas.plus.cloud/dev-ops/secret-init-container
    tag: "latest"
    pullPolicy: Always
  serviceAccountName: infrastructure-resource-provisioner
  address: http://openbao.security.svc.cluster.local:8200
  authPath: kubernetes
  role: xfsc-infrastructure-resource-provisioner
  kv:
    mount: infrastructure
    path: ""
  values:
    cassandra-password: '$RANDOM_64'
  transit:
    enabled: false
    engines: []

externalSecret:
  enabled: true
  apiVersion: external-secrets.io/v1
  refreshInterval: 15m
  store:
    name: openbao
    kind: SecretStore
  target:
    name: cassandra-root-auth
    creationPolicy: Owner
    deletionPolicy: Retain

cassandraRole:
  enabled: false

resourceProvider:
  enabled: true
  name: ""
  scope: Cluster
  description: Cassandra connection provided by this Helm release.
  allow:
    namespaces: []
  datacenter: dc1

cassandra:
  replicaCount: 1
  dbUser:
    user: cassandra
    existingSecret:
      name: cassandra-root-auth
      keyMapping:
        cassandra-password: cassandra-password
  cluster:
    name: cassandra
    datacenter: dc1
    rack: rack1
  persistence:
    enabled: true
    size: 8Gi
