{{- if and .Values.openbao.enabled .Values.clusterSecretStore.enabled }}
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.clusterSecretStore.name }}
spec:
  provider:
    vault:
      server: {{ .Values.openbao.address | quote }}
      path: {{ .Values.openbao.kvPath | quote }}
      version: v2
      auth:
        kubernetes:
          mountPath: {{ .Values.openbao.mountPath | quote }}
          role: {{ .Values.openbao.role | quote }}
          serviceAccountRef:
            name: {{ .Values.openbao.serviceAccount.name }}
            namespace: {{ .Values.openbao.serviceAccount.namespace }}
{{- end }}