credential-retrieval-service:
  replicaCount: 1
  name: credential-retrieval-service

  image:
    repository: node-654e3bca7fbeeed18f81d7c7.ps-xaas.io/ocm-wstack
    name: credential-retrieval-service
    tag: "0.0.0-dev"
    pullPolicy: Always

  podAnnotations: 
    inject.xfsc.io/enabled: "true"
    
  service:
    port: 8080
    type: ClusterIP
    addr: 0.0.0.0
  resources:
  security:
    runAsNonRoot: false
    runAsUid: 1000
    runAsGid: 1000

  config:
    disableTLS: true
    country: DE
    region: EU
    offeringTopic: offering
    offeringPolicy:
    metadataPolicy:
