loki:
 enabled: true
 persistence:
  enabled: true
  storageClassName: "cinder-default"
  size: 50Gi
 resources:
  limits:
    cpu: 450m
    memory: 2560Mi
  requests:
    cpu: 200m
    memory: 64Mi
promtail:
 enabled: true
 config:
    logLevel: info
    serverPort: 3101
    clients:
      - url: http://cao-monitoring-loki.cao-monitoring.svc.cluster.local:3100/loki/api/v1/push