{{- $password := (randAlpha 20) | b64enc }}
{{- $password2 := (randAlpha 20) | b64enc }}
{{- $password3 := (randAlpha 20) | b64enc }}
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-init-secrets
type: Opaque
data:
  username: YWRtaW4=
  password: {{ $password }}
  postgres-password: {{ $password2 }}
  admin-password: {{ $password3 }}