{{- if .Values.externalSecret.enabled }}
apiVersion: {{ .Values.externalSecret.apiVersion }}
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecret.target.name }}
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.store.name }}
    kind: {{ .Values.externalSecret.store.kind }}
  target:
    name: {{ .Values.externalSecret.target.name }}
    creationPolicy: {{ .Values.externalSecret.target.creationPolicy }}
    deletionPolicy: {{ .Values.externalSecret.target.deletionPolicy }}
  data:
    - secretKey: postgres-password
      remoteRef:
        key: {{ include "xfsc-postgresql.secretPath" . | quote }}
        property: postgres-password
{{- end }}
