{{- if .Values.externalSecret.enabled }}
apiVersion: {{ .Values.externalSecret.apiVersion }}
kind: ExternalSecret
metadata:
  name: {{ include "xfsc-postgresql-cnpg.superuserSecret" . }}
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.openbao.secretStore.name }}
    kind: SecretStore
  target:
    name: {{ include "xfsc-postgresql-cnpg.superuserSecret" . }}
    creationPolicy: {{ .Values.externalSecret.target.creationPolicy }}
    deletionPolicy: {{ .Values.externalSecret.target.deletionPolicy }}
    template:
      type: kubernetes.io/basic-auth
      metadata:
        labels:
          cnpg.io/reload: "true"
          cnpg.io/userType: superuser
  data:
    - secretKey: username
      remoteRef:
        key: {{ include "xfsc-postgresql-cnpg.secretPath" . | quote }}
        property: username
    - secretKey: password
      remoteRef:
        key: {{ include "xfsc-postgresql-cnpg.secretPath" . | quote }}
        property: password
{{- end }}
