{{- if .Values.resourceProvider.enabled }}
apiVersion: resources.xfsc.io/v1alpha1
kind: ResourceProvider
metadata:
  name: {{ default (printf "%s-postgres" .Release.Name) .Values.resourceProvider.name | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: resource-provider
spec:
  type: postgres
  scope: {{ .Values.resourceProvider.scope | quote }}
  description: {{ .Values.resourceProvider.description | quote }}
{{- with .Values.resourceProvider.allow.namespaces }}
  allow:
    namespaces:
{{ toYaml . | indent 6 }}
{{- end }}
  outputs:
    env:
      POSTGRES_HOST: {{ printf "%s-postgresql.%s.svc.cluster.local" .Release.Name .Release.Namespace | quote }}
      POSTGRES_PORT: "5432"
      POSTGRES_SSLMODE: {{ .Values.resourceProvider.sslMode | quote }}
{{- end }}
