apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ .Values.name }}
  namespace: argocd
  annotations:
    "helm.sh/resource-policy": keep
spec:
  sourceRepos:
    - 'https://github.com/eclipse-xfsc/deployment.git'
  destinations:
    - namespace: '*'
      server: '*'

  clusterResourceWhitelist:
    - group: '*'
      kind: '*'