apiVersion: v1
appVersion: v1.0.0
description: Policy Service
name: policy-service
version: 1.0.0
dependencies:
  - name: policy
    version: 1.4.3
    repository: oci://node-654e3bca7fbeeed18f81d7c7.ps-xaas.io/tsa
