{{- $secret := lookup "v1" "Secret" .Release.Namespace "minio-credentials" -}}
{{- $password := "" -}}

{{- if $secret }}
{{- $password = index $secret.data "root-password" | b64dec -}}
{{- else }}
{{- $password = randAlphaNum 32 -}}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
type: Opaque
stringData:
  root-user: admin
  root-password: {{ $password | quote }}