{{- if .Values.externalSecret.enabled }}
apiVersion: {{ .Values.externalSecret.apiVersion }}
kind: ExternalSecret
metadata:
  name: {{ include "minio.configSecret" . }}
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.openbao.secretStore.name }}
    kind: SecretStore
  target:
    name: {{ include "minio.configSecret" . }}
    creationPolicy: {{ .Values.externalSecret.target.creationPolicy }}
    deletionPolicy: {{ .Values.externalSecret.target.deletionPolicy }}
    template:
      data:
        config.env: |
          export MINIO_ROOT_USER={{ `{{ .rootUser }}` }}
          export MINIO_ROOT_PASSWORD={{ `{{ .rootPassword }}` }}
  data:
    - secretKey: rootUser
      remoteRef:
        key: {{ include "minio.secretPath" . | quote }}
        property: root-user
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
    - secretKey: rootPassword
      remoteRef:
        key: {{ include "minio.secretPath" . | quote }}
        property: root-password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
{{- end }}
