apiVersion: v2
name: xfsc-minio-openbao
description: Bitnami MinIO with OpenBao credential provisioning, ESO and S3 user provisioning
type: application
version: 0.1.0
appVersion: "2025.7.23"

dependencies:
  - name: minio
    version: ">=17.0.0 <18.0.0"
    repository: "https://charts.bitnami.com/bitnami"
