openbaoInit:
  enabled: true
  image:
    repository: node-654e3bca7fbeeed18f81d7c7.de-west-1.xaas.plus.cloud/dev-ops/secret-init-container
    tag: "latest"
    pullPolicy: Always
  serviceAccountName: infrastructure-resource-provisioner
  address: http://openbao.security.svc.cluster.local:8200
  authPath: kubernetes
  role: xfsc-infrastructure-resource-provisioner
  kv:
    mount: infrastructure
    path: ""
  values:
    root-user: minio-root
    root-password: '$RANDOM_64'
  transit:
    enabled: false
    engines: []

externalSecret:
  enabled: true
  apiVersion: external-secrets.io/v1
  refreshInterval: 15m
  store:
    name: openbao
    kind: SecretStore
  target:
    name: minio-root-auth
    creationPolicy: Owner
    deletionPolicy: Retain

minioUser:
  enabled: false

resourceProvider:
  enabled: true
  name: ""
  scope: Cluster
  description: S3-compatible connection provided by this MinIO Helm release.
  allow:
    namespaces: []
  scheme: http
  port: 9000
  region: us-east-1
  pathStyle: "true"

minio:
  mode: standalone
  auth:
    existingSecret: minio-root-auth
    rootUserSecretKey: root-user
    rootPasswordSecretKey: root-password
    usePasswordFiles: true
    useSecret: true
  defaultBuckets: ""
  persistence:
    enabled: true
    size: 8Gi
  networkPolicy:
    enabled: true
    allowExternal: true
