status-list-service:
  replicaCount: 1
  name: status-list-service

  image:
    repository: node-654e3bca7fbeeed18f81d7c7.ps-xaas.io/ocm-wstack
    name: status-list-service
    tag: "latest"
    sha: ""
    pullPolicy: Always
  podAnnotations: 
    inject.xfsc.io/enabled: "true"

  resources:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      cpu: 150m
      memory: 128Mi

  config:
    messaging:
      nats:
        queueGroup: statuslistservice
    servingPort: 8083
    creationTopic: status

