apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-web-ui-service
spec:
  selector:
    app: frontend-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: {{ .Values.frontendContainer.port }}
  type: {{ .Values.service.type }}