{{- if and .Values.global.kms.createSecret (eq .Values.global.kms.type "awskms") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.kms.aws.secretName }}
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.global.kms.aws.accessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.global.kms.aws.secretAccessKey | quote }}
{{- end }}

---
{{- if and .Values.global.kms.createSecret (eq .Values.global.kms.type "gcpckms") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.kms.gcp.secretName }}
type: Opaque
stringData:
  GOOGLE_APPLICATION_CREDENTIALS_JSON: |
{{ .Values.global.kms.gcp.credentialsJson | indent 4 }}
{{- end }}

---
{{- if and .Values.global.kms.createSecret (eq .Values.global.kms.type "azurekeyvault") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.kms.azure.secretName }}
type: Opaque
stringData:
  AZURE_TENANT_ID: {{ .Values.global.kms.azure.tenantId | quote }}
  AZURE_CLIENT_ID: {{ .Values.global.kms.azure.clientId | quote }}
  AZURE_CLIENT_SECRET: {{ .Values.global.kms.azure.clientSecret | quote }}
{{- end }}

---
{{- if and .Values.global.kms.createSecret (eq .Values.global.kms.type "transit") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.kms.transit.secretName }}
type: Opaque
stringData:
  token: {{ .Values.global.kms.transit.token | quote }}
{{- end }}