apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.provisioner.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: openbao-provisioner
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: openbao-provisioner
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-bootstrap
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-bootstrap
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: openbao-bootstrap

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-bootstrap
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-bootstrap
    app.kubernetes.io/instance: {{ .Release.Name }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch

  - apiGroups:
      - ""
    resources:
      - pods/exec
    verbs:
      - create

  - apiGroups:
      - ""
    resources:
      - secrets
      - configmaps
      - serviceaccounts
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-bootstrap
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-bootstrap
    app.kubernetes.io/instance: {{ .Release.Name }}
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-bootstrap
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-bootstrap