{{- if .Values.externalSecret.enabled }}
apiVersion: {{ .Values.externalSecret.apiVersion }}
kind: ExternalSecret
metadata:
  name: {{ include "redis.authSecret" . }}
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.openbao.secretStore.name }}
    kind: SecretStore
  target:
    name: {{ include "redis.authSecret" . }}
    creationPolicy: {{ .Values.externalSecret.target.creationPolicy }}
    deletionPolicy: {{ .Values.externalSecret.target.deletionPolicy }}
  data:
    - secretKey: password
      remoteRef:
        key: {{ include "redis.secretPath" . | quote }}
        property: password
{{- end }}
