{{- if .Values.resourceProvider.enabled }}
apiVersion: resources.xfsc.io/v1alpha1
kind: ResourceProvider
metadata:
  name: {{ default (printf "%s-redis" (include "redis.fullname" .)) .Values.resourceProvider.name | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace }}
spec:
  type: redis
  scope: {{ .Values.resourceProvider.scope | quote }}
  description: {{ .Values.resourceProvider.description | quote }}
{{- with .Values.resourceProvider.allow.namespaces }}
  allow:
    namespaces:
{{ toYaml . | indent 6 }}
{{- end }}
  outputs:
    env:
      REDIS_HOSTS: {{ printf "%s.%s.svc.cluster.local" (include "redis.fullname" .) .Release.Namespace | quote }}
      REDIS_PORT: "6379"
      REDIS_TLS: {{ .Values.resourceProvider.tls | quote }}
      REDIS_ISCLUSTER: {{ .Values.resourceProvider.cluster | quote }}
{{- end }}
