{{- if .Values.resourceProvider.enabled }}
apiVersion: resources.xfsc.io/v1alpha1
kind: ResourceProvider
metadata:
  name: {{ default (printf "%s-redis" (include "redis.fullname" .)) .Values.resourceProvider.name | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace }}
spec:
  type: redis
  scope: {{ .Values.resourceProvider.scope | quote }}
  description: {{ .Values.resourceProvider.description | quote }}
{{- with .Values.resourceProvider.allow.namespaces }}
  allow:
    namespaces:
{{ toYaml . | indent 6 }}
{{- end }}
  outputs:
    env:
      {{- if eq .Values.redis.mode "cluster" }}
      REDIS_HOSTS: {{ include "redis.clusterHosts" . | quote }}
      REDIS_ISCLUSTER: "true"
      {{- else }}
      REDIS_HOSTS: {{ printf "%s.%s.svc.cluster.local:%d"
        (include "redis.fullname" .)
        .Release.Namespace
        (int .Values.redis.port) | quote }}
      REDIS_ISCLUSTER: "false"
      {{- end }}

      REDIS_PORT: {{ .Values.redis.port | quote }}
      REDIS_TLS: {{ .Values.resourceProvider.tls | quote }}
{{- end }}
