{{- if .Values.openbao.secretStore.enabled }}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Values.openbao.secretStore.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  provider:
    vault:
      server: {{ .Values.openbao.address | quote }}
      path: {{ .Values.openbao.kvMount | quote }}
      version: v2
      auth:
        kubernetes:
          mountPath: {{ .Values.openbao.authPath | quote }}
          role: {{ .Values.openbao.role | quote }}
          serviceAccountRef:
            name: {{ .Values.openbao.serviceAccount.name }}
{{- end }}
