external-dns:
  provider:
    name: webhook
    webhook:
      image:
        repository: docker.io/hetzner/external-dns-hetzner-webhook
        tag: v0.2.0
      env:
        - name: HETZNER_TOKEN
          valueFrom:
            secretKeyRef:
              name: external-dns
              key: token

  domainFilters:
    - example.com

  sources:
    - ingress