external-dns:
  provider:
    name: webhook
    webhook:
      image:
        repository: ghcr.io/ionos-cloud/external-dns-webhook-ionos
        tag: latest
      env:
        - name: IONOS_API_KEY
          valueFrom:
            secretKeyRef:
              name: external-dns
              key: token

  domainFilters:
    - example.com