apiVersion: v2
name: xfsc-envoy-gateway
description: Minimal wrapper chart for Envoy Gateway without Gateway, listeners or routes
type: application
version: 0.1.0
appVersion: "1.8.3"
dependencies:
  - name: gateway-helm
    alias: envoy-gateway
    version: "1.8.3"
    repository: "oci://docker.io/envoyproxy"
    condition: envoy-gateway.enabled
