apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: {{ .Values.gatewayClass.name | default "envoy" | quote }}
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
  parametersRef:
    group: gateway.envoyproxy.io
    kind: EnvoyProxy
    name: {{ .Values.envoyProxy.name | default "envoy" | quote }}
    namespace: {{ .Values.gateway.namespace | default "infrastructure" | quote }}
