gatewayClass:
  name: envoy

envoy-gateway:
  enabled: true

  deployment:
    replicas: 1

  config:
    envoyGateway:
      logging:
        level:
          default: info

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

  provider:
    kubernetes:
      envoyService:
        type: LoadBalancer
        annotations:
          load-balancer.hetzner.cloud/network-zone: eu-central
          # alternativ statt network-zone:
          # load-balancer.hetzner.cloud/location: nbg1