apiVersion: v2
name: xfsc-cert-manager
description: XFSC cert-manager installation
type: application
version: 0.2.0
appVersion: "v1.21.0"
dependencies:
  - name: cert-manager
    version: v1.21.0
    repository: oci://quay.io/jetstack/charts
