tag: k8s-bootstrap
path: INFRA/basic/*
name: basic
namespace: infrastructure
storageClass: local-path

openbao:
  address: http://openbao.security.svc.cluster.local:8200
  authPath: kubernetes
  role: xfsc-infrastructure-resource-provisioner
  kvMount: infrastructure
  serviceAccount:
    name: infrastructure-resource-provisioner
  secretStore:
    enabled: true
    name: openbao

matrix:
  enabled: false

project:
  name: infrastructure
  description: Argo-CD-Projekt für Infrastruktur-Komponenten

  destinations:
    - server: https://kubernetes.default.svc
      namespace: infrastructure
    - server: https://kubernetes.default.svc
      namespace: kube-system