tag: k8s-bootstrap
path: INFRA/network/*
name: network
namespace: infrastructure
manageNamespace: true
excludes: 
 - "INFRA/network/bind9"
matrix: 
  enabled: false

project:
  name: infrastructure
  description: Argo-CD-Projekt für Infrastruktur-Komponenten

  destinations:
    - server: https://kubernetes.default.svc
      namespace: infrastructure
    - server: https://kubernetes.default.svc
      namespace: kube-system