tag: k8s-bootstrap
path: INFRA/core/*
name: core
namespace: infrastructure
matrix: 
  enabled: false

project:
  name: infrastructure
  description: Argo-CD-Projekt für Infrastruktur-Komponenten

  destinations:
    - server: https://kubernetes.default.svc
      namespace: infrastructure
    - server: https://kubernetes.default.svc
      namespace: kube-system