tag: k8s-bootstrap
path: "OCM W-Stack/*"
name: ocm-wstack
namespace: ocm-wstack
matrix: 
  enabled: false
excludes: 
 - "OCM W-Stack/tenant"
 - "OCM W-Stack/Policies"
 - "OCM W-Stack/Well Known Chart"
project:
  name: ocm-wstack
  description: Argo-CD-Projekt für ocm wstack
sourceRepos: 
  - https://github.com/eclipse-xfsc/deployment.git
  - node-654e3bca7fbeeed18f81d7c7.ps-xaas.io/ocm-wstack