tag: k8s-bootstrap
path: "OCM W-Stack/*"
name: ocm-wstack
namespace: ocm-wstack
matrix: 
  enabled: false
excludes: 
 - "OCM W-Stack/tenant"
project:
  name: ocm-wstack
  description: Argo-CD-Projekt für ocm wstack