openbao:
  enabled: true
  address: "http://openbao.security.svc.cluster.local:8200"
  mountPath: "kubernetes"
  role: "openbao-infra-eso"
  kvPath: "system"

  serviceAccount:
    name: eso-external-secrets
    namespace: security

clusterSecretStore:
  enabled: true
  name: system

secretStore:
  enabled: false
  name: system
  namespace: default