apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cao-sealed-secrets
    name: in-cluster
  project: train4-test2
  sources:
  - chart: sealed-secrets
    helm:
      releaseName: sealed-secrets
      valueFiles:
        - $values/train4-test2/values/values-sealed-secrets.yaml
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    targetRevision: 2.8.1
  - repoURL: https://gitlab.eclipse.org/eclipse/xfsc/train/infrastructure-as-code.git
    targetRevision: HEAD
    ref: values
    