{{- if .Values.certificate.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "xfsc-tenant-gateway.fullname" . }}
  labels:
    {{- include "xfsc-tenant-gateway.labels" . | nindent 4 }}
spec:
  secretName: {{ include "xfsc-tenant-gateway.tlsSecretName" . }}
  dnsNames:
    - {{ include "xfsc-tenant-gateway.hostname" . | quote }}
  issuerRef:
    name: {{ required "certificate.issuerRef.name is required" .Values.certificate.issuerRef.name | quote }}
    kind: {{ .Values.certificate.issuerRef.kind | default "ClusterIssuer" | quote }}
    group: {{ .Values.certificate.issuerRef.group | default "cert-manager.io" | quote }}
  {{- with .Values.certificate.duration }}
  duration: {{ . | quote }}
  {{- end }}
  {{- with .Values.certificate.renewBefore }}
  renewBefore: {{ . | quote }}
  {{- end }}
  privateKey:
    algorithm: {{ .Values.certificate.privateKey.algorithm | default "RSA" }}
    size: {{ .Values.certificate.privateKey.size | default 4096 }}
{{- end }}
