apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ .Values.name }}
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: https://github.com/eclipse-xfsc/deployment.git
        revision: {{ .Values.tag }}
        directories:
          - path: {{ .Values.path }}
  template:
    metadata:
      name: '{{ "{{ .path.basename | trim }}" }}'
    spec:
      project: default
      source:
        repoURL: https://github.com/eclipse-xfsc/deployment.git
        targetRevision:  {{ .Values.tag }}
        path: '{{ "{{ .path.path | trim }}" }}'
        helm:
          valueFiles:
            - values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace:  {{ .Values.namespace }}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true