apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ .Values.name }}
  namespace: argocd
spec:
  goTemplate: true

  generators:
{{- if (.Values.matrix.enabled | default false) }}
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/eclipse-xfsc/deployment.git
              revision: {{ .Values.tag }}
              directories:
                - path: {{ .Values.matrix.charts.path | quote }}
{{- range .Values.matrix.charts.excludes }}
                - path: {{ . | quote }}
                  exclude: true
{{- end }}

          - git:
              repoURL: https://github.com/eclipse-xfsc/deployment.git
              revision: {{ .Values.tag }}
              directories:
                - path: {{ .Values.matrix.values.path | quote }}
{{- range .Values.matrix.values.excludes }}
                - path: {{ . | quote }}
                  exclude: true
{{- end }}
{{- else }}
    - git:
        repoURL: https://github.com/eclipse-xfsc/deployment.git
        revision: {{ .Values.tag }}
        directories:
          - path: {{ .Values.path | quote }}
{{- range .Values.excludes }}
          - path: {{ . | quote }}
            exclude: true
{{- end }}
{{- end }}

  template:
    metadata:
{{- if (.Values.matrix.enabled | default false) }}
      name: '{{ "{{ .path.basename }}" }}-{{ "{{ .path.basename_1 }}" }}'
{{- else }}
      name: '{{ "{{ .path.basename }}" }}'
{{- end }}

    spec:
      project: default

      source:
        repoURL: https://github.com/eclipse-xfsc/deployment.git
        targetRevision: {{ .Values.tag }}

{{- if (.Values.matrix.enabled | default false) }}
        path: '{{ "{{ .path.path }}" }}'
        helm:
          valueFiles:
            - '../../../{{ "{{ .path_1.path }}" }}/values.yaml'
{{- if .Values.profile }}
            - '../../../{{ "{{ .path_1.path }}" }}/profiles/{{ .Values.profile }}.yaml'
{{- end }}
{{- else }}
        path: '{{ "{{ .path.path }}" }}'
        helm:
          valueFiles:
            - values.yaml
{{- if .Values.profile }}
            - 'profiles/{{ .Values.profile }}.yaml'
{{- end }}
{{- end }}

          parameters:
            - name: global.storageClass
              value: {{ .Values.storageClass | quote }}
{{- if .Values.domain }}
            - name: global.domain
              value: {{ .Values.domain | quote }}
            - name: domainFilters[0]
              value: {{ .Values.domain | quote }}
{{- end }}
{{- if .Values.profile }}
            - name: global.profile
              value: {{ .Values.profile | quote }}
{{- end }}


      destination:
        server: https://kubernetes.default.svc
        namespace: {{ .Values.namespace }}

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true