targetNamespace:
  create: true
  name: infrastructure
  labels:
    xsfc.io/zone: infrastructure

openbao:
  storeMountPath: infrastructure/openbao
  storeSecretPrefix: ""
  resourceProvisioner:
    serviceAccount:
      name: infrastructure-resource-provisioner
  storeReader:
    serviceAccount:
      name: infrastructure-store-reader
    permissions:
      engineManagement: true
      engineMountPrefix: infrastructure

clusterSecretStore:
  enabled: true
  name: infrastructure-openbao
  allowedNamespaces: []

secretStore:
  enabled: true
  name: openbao
