targetNamespace:
  create: true
  name: ocm-wstack
  labels:
    xsfc.io/zone: ocm-wstack

openbao:
  storeMountPath: apps/ocm-wstack/openbao
  storeSecretPrefix: ""
  resourceProvisioner:
    serviceAccount:
      name: ocm-wstack-resource-provisioner
  storeReader:
    serviceAccount:
      name: ocm-wstack-store-reader
    permissions:
      engineManagement: true
      engineMountPrefix: ocm-wstack

clusterSecretStore:
  enabled: true
  name: ocm-wstack-openbao
  allowedNamespaces: []

secretStore:
  enabled: true
  name: openbao
