targetNamespace:
  create: true
  name: ocm
  labels:
    xsfc.io/zone: ocm

openbao:
  storeMountPath: ocm/openbao
  storeSecretPrefix: ""
  resourceProvisioner:
    serviceAccount:
      name: ocm-resource-provisioner
  storeReader:
    serviceAccount:
      name: ocm-store-reader
    permissions:
      engineManagement: true
      engineMountPrefix: ocm

clusterSecretStore:
  enabled: true
  name: ocm-openbao
  allowedNamespaces: []

secretStore:
  enabled: true
  name: openbao
