targetNamespace:
  create: true
  name: ocm
  labels:
    xsfc.io/zone: ocm

openbao:
  storeMountPath: ocm
  storeSecretPrefix: ""
  resourceProvisioner:
    serviceAccount:
      name: ocm-resource-provisioner
  storeReader:
    serviceAccount:
      name: ocm-store-reader

clusterSecretStore:
  enabled: true
  name: ocm-openbao
  allowedNamespaces: []

secretStore:
  enabled: true
  name: openbao
