targetNamespace:
  create: true
  name: ocm
  labels:
    xsfc.io/zone: ocm

openbao:
  storeMountPath: ocm/openbao
  storeSecretPrefix: ""
  resourceProvisioner:
    engineMountPrefix: ocm
    serviceAccount:
      name: ocm-resource-provisioner
    tokenTTL: 15m
    tokenMaxTTL: 1h
    serviceToken:
      period: 0
      explicitMaxTTL: 0

clusterSecretStore:
  enabled: true
  name: ocm-openbao
  allowedNamespaces: []

secretStore:
  enabled: true
  name: openbao
