targetNamespace:
  create: true
  name: orce
  labels:
    xsfc.io/zone: orce

openbao:
  storeMountPath: orce/openbao
  storeSecretPrefix: ""
  resourceProvisioner:
    serviceAccount:
      name: orce-resource-provisioner
  storeReader:
    serviceAccount:
      name: orce-store-reader
    permissions:
      engineManagement: true
      engineMountPrefix: orce

clusterSecretStore:
  enabled: true
  name: orce-openbao
  allowedNamespaces: []

secretStore:
  enabled: true
  name: openbao
