targetNamespace:
  create: true
  name: tenants
  labels:
    xsfc.io/zone: tenants

openbao:
  storeMountPath: tenants/openbao
  storeSecretPrefix: ""
  resourceProvisioner:
    serviceAccount:
      name: tenants-resource-provisioner
  storeReader:
    serviceAccount:
      name: tenants-store-reader
    permissions:
      engineManagement: true
      engineMountPrefix: tenants

clusterSecretStore:
  enabled: true
  name: tenants-openbao
  allowedNamespaces: []

secretStore:
  enabled: true
  name: openbao
