
nginx-ingress:
  global:
    domain: ""
    storageClass: ""

  controller:
    replicaCount: 2

    service:
      type: LoadBalancer

    ingressClass:
      name: nginx
      create: true
      setAsDefaultIngress: true

    watchIngressWithoutClass: false

    enableCertManager: true

    config:
      entries:
        proxy-connect-timeout: "30s"
        proxy-read-timeout: "300s"
        proxy-send-timeout: "300s"

  externalDNS:
    enabled: true
    hostname: ${global.domain}