k8ssandra-operator:
  global:
    clusterScoped: true

  replicaCount: 1

  image:
    registry: docker.io
    repository: k8ssandra/k8ssandra-operator
    pullPolicy: IfNotPresent
    tag: ""

  controlPlane: true

  commonLabels:
    app.kubernetes.io/part-of: xfsc-infrastructure

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: "1"
      memory: 1Gi

  nodeSelector: {}
  tolerations: []
  affinity: {}
