apiVersion: v1
appVersion: v2.2.0
description: OpenBao Secrets Management
name: vault
version: 1.0.0

dependencies:
  - name: openbao
    alias: vault
    version: 0.16.0
    repository: https://openbao.github.io/openbao-helm