well-known-service:
  image: 
    pullPolicy: Always
  ingress:
   enabled: true
   annotations:
     kubernetes.io/ingress.class: nginx
     cert-manager.io/cluster-issuer: letsencrypt-prod
     nginx.ingress.kubernetes.io/rewrite-target: /v1/tenants/tenant_space/.well-known/openid-credential-issuer
   hosts:
     - host: cloud-wallet.DOMAIN
       paths:
         - path: /.well-known/openid-credential-issuer
           pathtype: ImplementationSpecific
           port: 8080
   tls:
     - secretName: xfsc-wildcard
       hosts:
         - cloud-wallet.DOMAIN
  config:
    loglevel: DEBUG
    isdev: false
    postgres:
      host: postgres-postgresql.NAMESPACE.svc.cluster.local       
      port: 5432
      database: wellknown
      user: postgres
      password: 
        key: postgresql-password
        name: wellknown-db-secret
      params: sslmode:disable
    nats:
      url: nats.NAMESPACE.svc.cluster.local:4222
      queuegroup: wellknown
    issuer: cloud-wallet.DOMAIN
    importer:
      broadcast:
