well-known-service:
  image: 
    tag: 0.0.0-dev
    pullPolicy: Always
  podAnnotations: 
    inject.xfsc.io/enabled: "true"
  
  config:
    loglevel: DEBUG
    isdev: false
    importer:
      broadcast:
