{{- if .Values.openbao.resourceProvisioner.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "app-namespace.resourceProvisionerServiceAccount" . }}
  namespace: {{ include "app-namespace.targetNamespace" . }}
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: openbao-resource-provisioner
{{- with .Values.openbao.resourceProvisioner.serviceAccount.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
---
{{- end }}
{{- if .Values.openbao.storeReader.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "app-namespace.storeReaderServiceAccount" . }}
  namespace: {{ include "app-namespace.targetNamespace" . }}
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: openbao-store-reader
{{- with .Values.openbao.storeReader.serviceAccount.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
{{- end }}
